name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image date
      run: docker build . --file Dockerfile --tag ghcr.io/adelerhof/docker-toolbox:$(date +%d%m%Y)
    - name: Push the Docker image date
      run: docker push ghcr.io/adelerhof/docker-toolbox:$(date +%d%m%Y)
    - name: Build the Docker image latest
      run: docker build . --file Dockerfile --tag ghcr.io/adelerhof/docker-toolbox:latest
    - name: Push the Docker image latest
      run: docker push ghcr.io/adelerhof/docker-toolbox:latest
