name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      # https://github.com/anothrNick/github-tag-action
      id: bump_version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch


    - name: Set releaase
      run: |
        echo "GITHUB_ORG="$(echo ${GITHUB_REPOSITORY} | sed 's/\/docker-.*//' ) >> $GITHUB_ENV
        echo "GITHUB_REPO="$(echo ${GITHUB_REPOSITORY} | sed 's/.*\/docker-//' ) >> $GITHUB_ENV
        echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
        cat $GITHUB_ENV

    - name: Checkout repository
      # https://github.com/actions/checkout
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      # https://github.com/docker/login-action
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      # https://github.com/docker/build-push-action
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{env.GITHUB_ORG}}/${{env.GITHUB_REPO}}:${{env.GITHUB_SHA}}
          ghcr.io/${{env.GITHUB_ORG}}/${{env.GITHUB_REPO}}:scan
          ghcr.io/${{env.GITHUB_ORG}}/${{env.GITHUB_REPO}}:${{ steps.bump_version.outputs.new_tag }}
          ghcr.io/${{env.GITHUB_ORG}}/${{env.GITHUB_REPO}}:latest

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{env.GITHUB_ORG}}/${{env.GITHUB_REPO}}:scan'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

    # - name: Build the Docker image date
    #   run: docker build . --file Dockerfile --tag ghcr.io/adelerhof/docker-toolbox:$(date +%d%m%Y)
    # - name: Push the Docker image date
    #   run: docker push ghcr.io/adelerhof/docker-toolbox:$(date +%d%m%Y)
    # - name: Build the Docker image latest
    #   run: docker build . --file Dockerfile --tag ghcr.io/adelerhof/docker-toolbox:latest
    # - name: Push the Docker image latest
    #   run: docker push ghcr.io/adelerhof/docker-toolbox:latest
